apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-laboratoire
  labels:
    app: frontend-laboratoire
spec:
  replicas: 3 # Nombre de pods répliqués pour gérer la charge
  selector:
    matchLabels:
      app: frontend-laboratoire
  template:
    metadata:
      labels:
        app: frontend-laboratoire
    spec:
      containers:
        - name: frontend-laboratoire
          image: loubnaidm/frontend-laboratoire:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-laboratoire-service
  labels:
    app: frontend-laboratoire
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend-laboratoire
